#!/bin/bash
# Include the aliases into a special file to source when log in
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias sl='sl -e'
alias LS='sl -e'
alias SL='sl -e'
alias CP='cp'
alias g='grep -insr'
alias f='find . -iname'
alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'
alias pwds='pwd>>~/dirs'
alias h='history|tail'
alias aiais='alias'
alias src='source ~/.bashrc'
alias vrc='vi ~/.bashrc'
alias vas='vi ~/.bash_aliases'
alias vvr='vi ~/.vimrc'
alias vdvb='vi drivers/media/platform/sdp/sdp-tsd/sdp-dvb.c'
alias gs='git status'
alias gg='git grep -in'
alias gp='git pull'
alias gpr='git pull --rebase'
alias grm='git rm'
alias gmv='git mv'
alias gd='git diff'
alias ga='git add'
alias gcm='git commit'
alias gac='git add .; git commit'
alias gl='git log --oneline -7'
alias gll='git log --pretty=oneline'
alias gss='git stash save'
alias gso='git stash show'
alias gsp='git stash pop'
alias gsd='git stash drop'
alias gb='git branch'
alias gck='git checkout'
alias gc='git gc'
alias gsh='git show'
alias gbm='git blame'
alias gcon='git config'
alias gcolor='git config --global --add color.ui true'
alias grh='git reset --hard'
alias grH='git reset HEAD'
alias gr='git remote'
alias k='cd /home/huangc/linux-tizentv'
alias hg='history | grep '
alias ag='alias | grep '
alias mnc='ps aux| grep minicom'
alias cdk='cd /home/huangc/linux-tizentv'
alias cdsa='cd /root/vdtz/drivers/media/platform/sdp-audio'
alias cdst='cd /root/vdtz/sound/soc/sdp-tz'
alias cds='cd /home/huangc/linux-tizentv/drivers/media/platform/sdp-tsd'
alias cdva='cd /root/vdtz/drivers/media/platform/sdp/sdp_audio'
alias cdvs='cd /root/vdtz/drivers/media/platform/sdp'
alias vsc='vi /root/vdtz/arch/arm/configs/sdp_defconfig'
alias vsd='vi arch/arm/configs/sdp_defconfig'
alias vdts='vi ./arch/arm/boot/dts/sdp1202-dtv.dts'
alias vdtsi='vi ./arch/arm/boot/dts/sdp1202.dtsi'
alias rmdtb='rm ./arch/arm/boot/dts/sdp1202-dtv.dtb'
alias gckdtb='git checkout ./arch/arm/boot/dts/sdp1202-dtv.dtb'
alias mc='make MENUCONFIG_COLOR=blackbg ARCH=arm menuconfig'
alias mm='make ARCH=arm modules'
alias ms='make ARCH=arm sdp_defconfig'
alias cmod='chmod -R o+w'
alias csdp='chmod -R o+w ./drivers/media/platform/sdp'
alias csa='chmod -R o+w ./drivers/media/platform/sdp-audio'
alias pg='ps aux | grep'
alias ig='ifconfig|grep'
alias cmds='history|tail>>~/cmds'
alias fip='ifconfig eth0 | grep "inet addr"'
