#!/bin/bash
# Include the aliases into a special file to source when log in
# Configuration about the bash command aliases

alias vi='vim'
alias ..='cd ../'
alias ...='cd ../../'
alias ....='cd ../../../'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias ls='ls --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias sl='sl -e'
alias LS='sl -e'
alias SL='sl -e'
alias CP='cp'
alias g='grep -insr'
alias f='find . -iname'
alias pwds='pwd>>~/dirs'
alias h='history|tail'
alias aiais='alias'
alias src='source ~/.bashrc'
alias vrc='vi ~/.bashrc'
alias vas='vi ~/.bash_aliases'
alias vvr='vi ~/.vimrc'
alias gs='git status'
alias gg='git grep -in'
alias gp='git pull'
alias gpr='git pull --rebase'
alias grm='git rm'
alias gmv='git mv'
alias gd='git diff'
alias ga='git add'
alias gcm='git commit'
alias gac='git add .; git commit'
alias gl='git log --oneline -7'
alias gll='git log --pretty=oneline'
alias gss='git stash save'
alias gso='git stash show'
alias gsp='git stash pop'
alias gsd='git stash drop'
alias gb='git branch'
alias gck='git checkout'
alias gc='git gc'
alias gsh='git show'
alias gbm='git blame'
alias gcon='git config'
alias gcolor='git config --global --add color.ui true'
alias gedit='git config --global --add core.editor vim'
alias grh='git reset --hard'
alias grH='git reset HEAD'
alias gr='git remote'
alias hg='history | grep '
alias ag='alias | grep '
alias mnc='ps aux| grep minicom'
alias mc='make MENUCONFIG_COLOR=blackbg ARCH=arm menuconfig'
alias mm='make ARCH=arm modules'
alias msdp='make ARCH=arm sdp_defconfig'
alias cmod='chmod -R o+w'
alias pg='ps aux | grep'
alias ig='ifconfig|grep'
alias cmds='history|tail>>~/cmds'
alias fip='ifconfig eth0 | grep "inet addr"'
alias tag='rm -f tags cscope.*;ctags -R;cscope -Rbkq'
